[package]
name = "guessing_game"
version = "0.1.0"
authors = ["Austin Rooks <austin@r00ks.io>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

rand = "0.4.0"